# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chose_dict_data_v2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(789, 729)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(610, 130, 151, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 210, 151, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(50, 70, 481, 481))
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(56)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(50, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(51, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(52, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(53, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(54, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(55, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(21, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(21, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(28, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(28, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(28, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(35, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(35, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(35, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(42, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(42, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(42, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(49, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(49, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(49, 2, item)
        self.tableWidget.verticalHeader().setVisible(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Загрузить из Excel"))
        self.pushButton_2.setText(_translate("Dialog", "Принять"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "_"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "in1_"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "crest_"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "in2_"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "pinch_"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "out1_"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "out2_"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "_"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "in1_"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "crest_"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "in2_"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "pinch_"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "out1_"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "out2_"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "_"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "in1_"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "crest_"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "in2_"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("Dialog", "pinch_"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("Dialog", "out1_"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("Dialog", "out2_"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("Dialog", "_"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("Dialog", "in1_"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("Dialog", "crest_"))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("Dialog", "in2_"))
        item = self.tableWidget.verticalHeaderItem(25)
        item.setText(_translate("Dialog", "pinch_"))
        item = self.tableWidget.verticalHeaderItem(26)
        item.setText(_translate("Dialog", "out1_"))
        item = self.tableWidget.verticalHeaderItem(27)
        item.setText(_translate("Dialog", "out2_"))
        item = self.tableWidget.verticalHeaderItem(28)
        item.setText(_translate("Dialog", "_"))
        item = self.tableWidget.verticalHeaderItem(29)
        item.setText(_translate("Dialog", "in1_"))
        item = self.tableWidget.verticalHeaderItem(30)
        item.setText(_translate("Dialog", "crest_"))
        item = self.tableWidget.verticalHeaderItem(31)
        item.setText(_translate("Dialog", "in2_"))
        item = self.tableWidget.verticalHeaderItem(32)
        item.setText(_translate("Dialog", "pinch_"))
        item = self.tableWidget.verticalHeaderItem(33)
        item.setText(_translate("Dialog", "out1_"))
        item = self.tableWidget.verticalHeaderItem(34)
        item.setText(_translate("Dialog", "out2_"))
        item = self.tableWidget.verticalHeaderItem(35)
        item.setText(_translate("Dialog", "_"))
        item = self.tableWidget.verticalHeaderItem(36)
        item.setText(_translate("Dialog", "in1_"))
        item = self.tableWidget.verticalHeaderItem(37)
        item.setText(_translate("Dialog", "crest_"))
        item = self.tableWidget.verticalHeaderItem(38)
        item.setText(_translate("Dialog", "in2_"))
        item = self.tableWidget.verticalHeaderItem(39)
        item.setText(_translate("Dialog", "pinch_"))
        item = self.tableWidget.verticalHeaderItem(40)
        item.setText(_translate("Dialog", "out1_"))
        item = self.tableWidget.verticalHeaderItem(41)
        item.setText(_translate("Dialog", "out2_"))
        item = self.tableWidget.verticalHeaderItem(42)
        item.setText(_translate("Dialog", "_"))
        item = self.tableWidget.verticalHeaderItem(43)
        item.setText(_translate("Dialog", "in1_"))
        item = self.tableWidget.verticalHeaderItem(44)
        item.setText(_translate("Dialog", "crest_"))
        item = self.tableWidget.verticalHeaderItem(45)
        item.setText(_translate("Dialog", "in2_"))
        item = self.tableWidget.verticalHeaderItem(46)
        item.setText(_translate("Dialog", "pinch_"))
        item = self.tableWidget.verticalHeaderItem(47)
        item.setText(_translate("Dialog", "out1_"))
        item = self.tableWidget.verticalHeaderItem(48)
        item.setText(_translate("Dialog", "out2_"))
        item = self.tableWidget.verticalHeaderItem(49)
        item.setText(_translate("Dialog", "_"))
        item = self.tableWidget.verticalHeaderItem(50)
        item.setText(_translate("Dialog", "in1_"))
        item = self.tableWidget.verticalHeaderItem(51)
        item.setText(_translate("Dialog", "crest_"))
        item = self.tableWidget.verticalHeaderItem(52)
        item.setText(_translate("Dialog", "in2_"))
        item = self.tableWidget.verticalHeaderItem(53)
        item.setText(_translate("Dialog", "pinch_"))
        item = self.tableWidget.verticalHeaderItem(54)
        item.setText(_translate("Dialog", "out1_"))
        item = self.tableWidget.verticalHeaderItem(55)
        item.setText(_translate("Dialog", "out2_"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "a"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "b"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "c"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "14"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Dialog", "13"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("Dialog", "12"))
        item = self.tableWidget.item(21, 0)
        item.setText(_translate("Dialog", "11"))
        item = self.tableWidget.item(28, 0)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.item(35, 0)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget.item(42, 0)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget.item(49, 0)
        item.setText(_translate("Dialog", "7"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
