# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prog_rasch_interface_v12.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1017, 907)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.header = QtWidgets.QGridLayout()
        self.header.setSpacing(0)
        self.header.setObjectName("header")
        self.btn_rosniti_about = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rosniti_about.sizePolicy().hasHeightForWidth())
        self.btn_rosniti_about.setSizePolicy(sizePolicy)
        self.btn_rosniti_about.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_rosniti_about.setMaximumSize(QtCore.QSize(52, 72))
        self.btn_rosniti_about.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_rosniti_about.setStyleSheet("QPushButton:pressed { background-color: rgb(0, 255, 255, 20); }")
        self.btn_rosniti_about.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/logo_rosniti.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rosniti_about.setIcon(icon1)
        self.btn_rosniti_about.setIconSize(QtCore.QSize(52, 72))
        self.btn_rosniti_about.setFlat(True)
        self.btn_rosniti_about.setObjectName("btn_rosniti_about")
        self.header.addWidget(self.btn_rosniti_about, 0, 2, 1, 1)
        self.btn_vtz_about = QtWidgets.QPushButton(self.centralwidget)
        self.btn_vtz_about.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_vtz_about.setMaximumSize(QtCore.QSize(52, 72))
        self.btn_vtz_about.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_vtz_about.setStyleSheet("QPushButton:pressed { background-color: rgb(0, 255, 255, 20); }")
        self.btn_vtz_about.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/logo_vtz.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_vtz_about.setIcon(icon2)
        self.btn_vtz_about.setIconSize(QtCore.QSize(52, 72))
        self.btn_vtz_about.setFlat(True)
        self.btn_vtz_about.setObjectName("btn_vtz_about")
        self.header.addWidget(self.btn_vtz_about, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(193, 193, 193)")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.header.addWidget(self.label_14, 0, 1, 1, 1)
        self.btn_secret_behind_vtz_logo = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_secret_behind_vtz_logo.sizePolicy().hasHeightForWidth())
        self.btn_secret_behind_vtz_logo.setSizePolicy(sizePolicy)
        self.btn_secret_behind_vtz_logo.setMinimumSize(QtCore.QSize(1, 1))
        self.btn_secret_behind_vtz_logo.setMaximumSize(QtCore.QSize(1, 1))
        self.btn_secret_behind_vtz_logo.setText("")
        self.btn_secret_behind_vtz_logo.setObjectName("btn_secret_behind_vtz_logo")
        self.header.addWidget(self.btn_secret_behind_vtz_logo, 0, 3, 1, 1)
        self.gridLayout_22.addLayout(self.header, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 982, 795))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.tab_analysis = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tab_analysis.setMinimumSize(QtCore.QSize(921, 701))
        self.tab_analysis.setMaximumSize(QtCore.QSize(1111111, 1111111))
        self.tab_analysis.setBaseSize(QtCore.QSize(921, 701))
        self.tab_analysis.setDocumentMode(True)
        self.tab_analysis.setObjectName("tab_analysis")
        self.Count = QtWidgets.QWidget()
        self.Count.setObjectName("Count")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Count)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.both = QtWidgets.QGridLayout()
        self.both.setHorizontalSpacing(14)
        self.both.setVerticalSpacing(6)
        self.both.setObjectName("both")
        self.frameLeftColumn = QtWidgets.QFrame(self.Count)
        self.frameLeftColumn.setMinimumSize(QtCore.QSize(303, 661))
        self.frameLeftColumn.setMaximumSize(QtCore.QSize(321, 11111111))
        self.frameLeftColumn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLeftColumn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLeftColumn.setObjectName("frameLeftColumn")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameLeftColumn)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.leftColumn = QtWidgets.QGridLayout()
        self.leftColumn.setContentsMargins(4, 2, 4, 2)
        self.leftColumn.setObjectName("leftColumn")
        self.firstLayParam = QtWidgets.QGridLayout()
        self.firstLayParam.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.firstLayParam.setObjectName("firstLayParam")
        self.ent_Doh = QtWidgets.QComboBox(self.frameLeftColumn)
        self.ent_Doh.setEditable(True)
        self.ent_Doh.setObjectName("ent_Doh")
        self.ent_Doh.addItem("")
        self.firstLayParam.addWidget(self.ent_Doh, 2, 2, 1, 2)
        self.label_39 = QtWidgets.QLabel(self.frameLeftColumn)
        self.label_39.setMaximumSize(QtCore.QSize(189, 20))
        self.label_39.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_39.setObjectName("label_39")
        self.firstLayParam.addWidget(self.label_39, 2, 0, 1, 2)
        self.label_38 = QtWidgets.QLabel(self.frameLeftColumn)
        self.label_38.setMaximumSize(QtCore.QSize(189, 20))
        self.label_38.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_38.setObjectName("label_38")
        self.firstLayParam.addWidget(self.label_38, 1, 0, 1, 2)
        self.ent_billet_length = QtWidgets.QSpinBox(self.frameLeftColumn)
        self.ent_billet_length.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ent_billet_length.setWrapping(False)
        self.ent_billet_length.setFrame(True)
        self.ent_billet_length.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ent_billet_length.setAccelerated(False)
        self.ent_billet_length.setKeyboardTracking(False)
        self.ent_billet_length.setMinimum(1)
        self.ent_billet_length.setMaximum(100000)
        self.ent_billet_length.setSingleStep(1)
        self.ent_billet_length.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ent_billet_length.setProperty("value", 3600)
        self.ent_billet_length.setDisplayIntegerBase(10)
        self.ent_billet_length.setObjectName("ent_billet_length")
        self.firstLayParam.addWidget(self.ent_billet_length, 1, 2, 1, 2)
        self.ent_D1 = QtWidgets.QComboBox(self.frameLeftColumn)
        self.ent_D1.setEditable(True)
        self.ent_D1.setObjectName("ent_D1")
        self.ent_D1.addItem("")
        self.firstLayParam.addWidget(self.ent_D1, 0, 2, 1, 2)
        self.label_40 = QtWidgets.QLabel(self.frameLeftColumn)
        self.label_40.setMaximumSize(QtCore.QSize(189, 20))
        self.label_40.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_40.setObjectName("label_40")
        self.firstLayParam.addWidget(self.label_40, 0, 0, 1, 2)
        self.leftColumn.addLayout(self.firstLayParam, 0, 0, 1, 1)
        self.frame_with_fact = QtWidgets.QFrame(self.frameLeftColumn)
        self.frame_with_fact.setEnabled(True)
        self.frame_with_fact.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_with_fact.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_with_fact.setObjectName("frame_with_fact")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.frame_with_fact)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_27 = QtWidgets.QLabel(self.frame_with_fact)
        self.label_27.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_27.setObjectName("label_27")
        self.gridLayout_9.addWidget(self.label_27, 0, 0, 1, 1)
        self.get_real_pc = QtWidgets.QComboBox(self.frame_with_fact)
        self.get_real_pc.setObjectName("get_real_pc")
        self.get_real_pc.addItem("")
        self.get_real_pc.addItem("")
        self.gridLayout_9.addWidget(self.get_real_pc, 1, 0, 1, 1)
        self.get_real_result = QtWidgets.QSpinBox(self.frame_with_fact)
        self.get_real_result.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.get_real_result.setMinimum(200)
        self.get_real_result.setMaximum(10000)
        self.get_real_result.setProperty("value", 2222)
        self.get_real_result.setObjectName("get_real_result")
        self.gridLayout_9.addWidget(self.get_real_result, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_with_fact)
        self.label_28.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_28.setObjectName("label_28")
        self.gridLayout_9.addWidget(self.label_28, 0, 1, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.leftColumn.addWidget(self.frame_with_fact, 6, 0, 1, 1)
        self.frame_with_reduction = QtWidgets.QFrame(self.frameLeftColumn)
        self.frame_with_reduction.setEnabled(True)
        self.frame_with_reduction.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_with_reduction.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_with_reduction.setObjectName("frame_with_reduction")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.frame_with_reduction)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_55 = QtWidgets.QLabel(self.frame_with_reduction)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_14.addWidget(self.label_55, 1, 3, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.frame_with_reduction)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_59.setObjectName("label_59")
        self.gridLayout_14.addWidget(self.label_59, 0, 0, 1, 4)
        self.label_54 = QtWidgets.QLabel(self.frame_with_reduction)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.gridLayout_14.addWidget(self.label_54, 1, 1, 1, 1)
        self.set_piercing_percent = QtWidgets.QDoubleSpinBox(self.frame_with_reduction)
        self.set_piercing_percent.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.set_piercing_percent.setSingleStep(0.01)
        self.set_piercing_percent.setProperty("value", 2.0)
        self.set_piercing_percent.setObjectName("set_piercing_percent")
        self.gridLayout_14.addWidget(self.set_piercing_percent, 1, 2, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.frame_with_reduction)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_14.addWidget(self.label_56, 3, 3, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.frame_with_reduction)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_14.addWidget(self.label_57, 3, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.frame_with_reduction)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_14.addWidget(self.label_58, 2, 0, 1, 4)
        self.set_piercing_mm = QtWidgets.QDoubleSpinBox(self.frame_with_reduction)
        self.set_piercing_mm.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.set_piercing_mm.setSingleStep(0.01)
        self.set_piercing_mm.setObjectName("set_piercing_mm")
        self.gridLayout_14.addWidget(self.set_piercing_mm, 1, 0, 1, 1)
        self.set_colib_mm = QtWidgets.QDoubleSpinBox(self.frame_with_reduction)
        self.set_colib_mm.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.set_colib_mm.setSingleStep(0.01)
        self.set_colib_mm.setProperty("value", 3.0)
        self.set_colib_mm.setObjectName("set_colib_mm")
        self.gridLayout_14.addWidget(self.set_colib_mm, 3, 0, 1, 1)
        self.set_colib_percent = QtWidgets.QDoubleSpinBox(self.frame_with_reduction)
        self.set_colib_percent.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.set_colib_percent.setSingleStep(0.01)
        self.set_colib_percent.setObjectName("set_colib_percent")
        self.gridLayout_14.addWidget(self.set_colib_percent, 3, 2, 1, 1)
        self.gridLayout_14.setColumnStretch(0, 3)
        self.gridLayout_14.setColumnStretch(1, 1)
        self.gridLayout_14.setColumnStretch(2, 3)
        self.gridLayout_14.setColumnStretch(3, 1)
        self.gridLayout_32.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.leftColumn.addWidget(self.frame_with_reduction, 2, 0, 1, 1)
        self.check_manual_reduction = QtWidgets.QCheckBox(self.frameLeftColumn)
        self.check_manual_reduction.setObjectName("check_manual_reduction")
        self.leftColumn.addWidget(self.check_manual_reduction, 1, 0, 1, 1)
        self.secondLayParam = QtWidgets.QGridLayout()
        self.secondLayParam.setObjectName("secondLayParam")
        self.label_46 = QtWidgets.QLabel(self.frameLeftColumn)
        self.label_46.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_46.setObjectName("label_46")
        self.secondLayParam.addWidget(self.label_46, 4, 0, 1, 2)
        self.label_47 = QtWidgets.QLabel(self.frameLeftColumn)
        self.label_47.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_47.setObjectName("label_47")
        self.secondLayParam.addWidget(self.label_47, 3, 0, 1, 2)
        self.ent_nd = QtWidgets.QSpinBox(self.frameLeftColumn)
        self.ent_nd.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ent_nd.setWrapping(False)
        self.ent_nd.setFrame(True)
        self.ent_nd.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ent_nd.setAccelerated(False)
        self.ent_nd.setKeyboardTracking(False)
        self.ent_nd.setMinimum(1)
        self.ent_nd.setMaximum(100000)
        self.ent_nd.setSingleStep(1)
        self.ent_nd.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ent_nd.setProperty("value", 200)
        self.ent_nd.setDisplayIntegerBase(10)
        self.ent_nd.setObjectName("ent_nd")
        self.secondLayParam.addWidget(self.ent_nd, 3, 2, 1, 2)
        self.choose_colib = QtWidgets.QComboBox(self.frameLeftColumn)
        self.choose_colib.setObjectName("choose_colib")
        self.choose_colib.addItem("")
        self.choose_colib.addItem("")
        self.choose_colib.addItem("")
        self.secondLayParam.addWidget(self.choose_colib, 4, 2, 1, 2)
        self.ent_Dvp = QtWidgets.QSpinBox(self.frameLeftColumn)
        self.ent_Dvp.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ent_Dvp.setWrapping(False)
        self.ent_Dvp.setFrame(True)
        self.ent_Dvp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ent_Dvp.setAccelerated(False)
        self.ent_Dvp.setKeyboardTracking(False)
        self.ent_Dvp.setMinimum(1)
        self.ent_Dvp.setMaximum(100000)
        self.ent_Dvp.setSingleStep(1)
        self.ent_Dvp.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ent_Dvp.setProperty("value", 535)
        self.ent_Dvp.setDisplayIntegerBase(10)
        self.ent_Dvp.setObjectName("ent_Dvp")
        self.secondLayParam.addWidget(self.ent_Dvp, 2, 2, 1, 2)
        self.label_48 = QtWidgets.QLabel(self.frameLeftColumn)
        self.label_48.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_48.setObjectName("label_48")
        self.secondLayParam.addWidget(self.label_48, 2, 0, 1, 2)
        self.ent_beta = QtWidgets.QComboBox(self.frameLeftColumn)
        self.ent_beta.setEnabled(True)
        self.ent_beta.setEditable(False)
        self.ent_beta.setObjectName("ent_beta")
        self.ent_beta.addItem("")
        self.ent_beta.addItem("")
        self.ent_beta.addItem("")
        self.ent_beta.addItem("")
        self.ent_beta.addItem("")
        self.ent_beta.addItem("")
        self.ent_beta.addItem("")
        self.secondLayParam.addWidget(self.ent_beta, 1, 2, 1, 2)
        self.label_45 = QtWidgets.QLabel(self.frameLeftColumn)
        self.label_45.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_45.setObjectName("label_45")
        self.secondLayParam.addWidget(self.label_45, 1, 0, 1, 2)
        self.ent_T = QtWidgets.QSpinBox(self.frameLeftColumn)
        self.ent_T.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ent_T.setWrapping(False)
        self.ent_T.setFrame(True)
        self.ent_T.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ent_T.setAccelerated(False)
        self.ent_T.setKeyboardTracking(False)
        self.ent_T.setMinimum(1000)
        self.ent_T.setMaximum(1300)
        self.ent_T.setSingleStep(1)
        self.ent_T.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ent_T.setProperty("value", 1160)
        self.ent_T.setDisplayIntegerBase(10)
        self.ent_T.setObjectName("ent_T")
        self.secondLayParam.addWidget(self.ent_T, 0, 2, 1, 2)
        self.label_49 = QtWidgets.QLabel(self.frameLeftColumn)
        self.label_49.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_49.setObjectName("label_49")
        self.secondLayParam.addWidget(self.label_49, 0, 0, 1, 2)
        self.leftColumn.addLayout(self.secondLayParam, 3, 0, 1, 1)
        self.check_fact = QtWidgets.QCheckBox(self.frameLeftColumn)
        self.check_fact.setObjectName("check_fact")
        self.leftColumn.addWidget(self.check_fact, 5, 0, 1, 1)
        self.btn_count = QtWidgets.QPushButton(self.frameLeftColumn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btn_count.sizePolicy().hasHeightForWidth())
        self.btn_count.setSizePolicy(sizePolicy)
        self.btn_count.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_count.setMaximumSize(QtCore.QSize(1111111, 50))
        self.btn_count.setSizeIncrement(QtCore.QSize(0, 2))
        self.btn_count.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_count.setFont(font)
        self.btn_count.setAutoDefault(True)
        self.btn_count.setDefault(True)
        self.btn_count.setFlat(False)
        self.btn_count.setObjectName("btn_count")
        self.leftColumn.addWidget(self.btn_count, 8, 0, 1, 1)
        self.btn_go_to_analysis = QtWidgets.QCommandLinkButton(self.frameLeftColumn)
        self.btn_go_to_analysis.setMaximumSize(QtCore.QSize(600, 250))
        self.btn_go_to_analysis.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_go_to_analysis.setObjectName("btn_go_to_analysis")
        self.leftColumn.addWidget(self.btn_go_to_analysis, 7, 0, 1, 1)
        self.frameChooseSteel = QtWidgets.QFrame(self.frameLeftColumn)
        self.frameChooseSteel.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameChooseSteel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameChooseSteel.setLineWidth(2)
        self.frameChooseSteel.setMidLineWidth(3)
        self.frameChooseSteel.setObjectName("frameChooseSteel")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameChooseSteel)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.discard_steel = QtWidgets.QPushButton(self.frameChooseSteel)
        self.discard_steel.setObjectName("discard_steel")
        self.gridLayout_13.addWidget(self.discard_steel, 3, 1, 1, 1)
        self.choose_steel = QtWidgets.QComboBox(self.frameChooseSteel)
        self.choose_steel.setEditable(True)
        self.choose_steel.setObjectName("choose_steel")
        self.choose_steel.addItem("")
        self.choose_steel.addItem("")
        self.choose_steel.addItem("")
        self.gridLayout_13.addWidget(self.choose_steel, 2, 0, 1, 1)
        self.add_steel = QtWidgets.QPushButton(self.frameChooseSteel)
        self.add_steel.setObjectName("add_steel")
        self.gridLayout_13.addWidget(self.add_steel, 2, 1, 1, 1)
        self.btn_refresh = QtWidgets.QPushButton(self.frameChooseSteel)
        self.btn_refresh.setObjectName("btn_refresh")
        self.gridLayout_13.addWidget(self.btn_refresh, 1, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.frameChooseSteel)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_51.setObjectName("label_51")
        self.gridLayout_13.addWidget(self.label_51, 0, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.leftColumn.addWidget(self.frameChooseSteel, 4, 0, 1, 1)
        self.leftColumn.setRowMinimumHeight(0, 100)
        self.leftColumn.setRowMinimumHeight(2, 110)
        self.leftColumn.setRowMinimumHeight(3, 140)
        self.leftColumn.setRowMinimumHeight(4, 130)
        self.leftColumn.setRowMinimumHeight(6, 60)
        self.gridLayout_2.addLayout(self.leftColumn, 0, 0, 1, 1)
        self.both.addWidget(self.frameLeftColumn, 0, 0, 1, 1)
        self.frameRIGHT = QtWidgets.QFrame(self.Count)
        self.frameRIGHT.setMinimumSize(QtCore.QSize(650, 0))
        self.frameRIGHT.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRIGHT.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRIGHT.setObjectName("frameRIGHT")
        self.gridLayout = QtWidgets.QGridLayout(self.frameRIGHT)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.rightColumn = QtWidgets.QGridLayout()
        self.rightColumn.setVerticalSpacing(14)
        self.rightColumn.setObjectName("rightColumn")
        self.graph = QtWidgets.QGridLayout()
        self.graph.setContentsMargins(-1, 2, -1, -1)
        self.graph.setVerticalSpacing(10)
        self.graph.setObjectName("graph")
        self.label_43 = QtWidgets.QLabel(self.frameRIGHT)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.graph.addWidget(self.label_43, 0, 0, 1, 2)
        self.listWidget = QtWidgets.QListWidget(self.frameRIGHT)
        self.listWidget.setObjectName("listWidget")
        self.graph.addWidget(self.listWidget, 1, 0, 1, 2)
        self.rightColumn.addLayout(self.graph, 0, 0, 1, 1)
        self.allResults = QtWidgets.QGridLayout()
        self.allResults.setContentsMargins(8, 8, 8, 8)
        self.allResults.setHorizontalSpacing(18)
        self.allResults.setVerticalSpacing(8)
        self.allResults.setObjectName("allResults")
        self.get_sum_reduction = QtWidgets.QLineEdit(self.frameRIGHT)
        self.get_sum_reduction.setEnabled(False)
        self.get_sum_reduction.setMinimumSize(QtCore.QSize(93, 20))
        self.get_sum_reduction.setMaximumSize(QtCore.QSize(93, 20))
        self.get_sum_reduction.setObjectName("get_sum_reduction")
        self.allResults.addWidget(self.get_sum_reduction, 4, 4, 1, 1)
        self.get_mu = QtWidgets.QLineEdit(self.frameRIGHT)
        self.get_mu.setEnabled(False)
        self.get_mu.setMinimumSize(QtCore.QSize(93, 20))
        self.get_mu.setMaximumSize(QtCore.QSize(93, 20))
        self.get_mu.setObjectName("get_mu")
        self.allResults.addWidget(self.get_mu, 2, 4, 1, 1)
        self.mainResults = QtWidgets.QFrame(self.frameRIGHT)
        self.mainResults.setFrameShape(QtWidgets.QFrame.Box)
        self.mainResults.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainResults.setObjectName("mainResults")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.mainResults)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.get_PC2 = QtWidgets.QLineEdit(self.mainResults)
        self.get_PC2.setEnabled(False)
        self.get_PC2.setMinimumSize(QtCore.QSize(100, 20))
        self.get_PC2.setMaximumSize(QtCore.QSize(100, 20))
        self.get_PC2.setObjectName("get_PC2")
        self.gridLayout_8.addWidget(self.get_PC2, 1, 4, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.mainResults)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_41.setObjectName("label_41")
        self.gridLayout_8.addWidget(self.label_41, 1, 3, 1, 1)
        self.get_forged_len_5 = QtWidgets.QLineEdit(self.mainResults)
        self.get_forged_len_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_forged_len_5.sizePolicy().hasHeightForWidth())
        self.get_forged_len_5.setSizePolicy(sizePolicy)
        self.get_forged_len_5.setMinimumSize(QtCore.QSize(1, 1))
        self.get_forged_len_5.setFrame(False)
        self.get_forged_len_5.setObjectName("get_forged_len_5")
        self.gridLayout_8.addWidget(self.get_forged_len_5, 1, 5, 1, 1)
        self.get_PC1 = QtWidgets.QLineEdit(self.mainResults)
        self.get_PC1.setEnabled(False)
        self.get_PC1.setMinimumSize(QtCore.QSize(100, 20))
        self.get_PC1.setMaximumSize(QtCore.QSize(100, 20))
        self.get_PC1.setObjectName("get_PC1")
        self.gridLayout_8.addWidget(self.get_PC1, 1, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.mainResults)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 1, 1, 1, 1)
        self.get_forged_len_6 = QtWidgets.QLineEdit(self.mainResults)
        self.get_forged_len_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_forged_len_6.sizePolicy().hasHeightForWidth())
        self.get_forged_len_6.setSizePolicy(sizePolicy)
        self.get_forged_len_6.setMinimumSize(QtCore.QSize(1, 1))
        self.get_forged_len_6.setFrame(False)
        self.get_forged_len_6.setObjectName("get_forged_len_6")
        self.gridLayout_8.addWidget(self.get_forged_len_6, 1, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.mainResults)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 0, 0, 1, 6)
        self.gridLayout_8.setColumnStretch(0, 2)
        self.gridLayout_8.setColumnStretch(5, 2)
        self.gridLayout_21.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.allResults.addWidget(self.mainResults, 0, 0, 1, 6)
        self.label_37 = QtWidgets.QLabel(self.frameRIGHT)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_37.setObjectName("label_37")
        self.allResults.addWidget(self.label_37, 3, 1, 1, 1)
        self.get_reduction_time = QtWidgets.QLineEdit(self.frameRIGHT)
        self.get_reduction_time.setEnabled(False)
        self.get_reduction_time.setMinimumSize(QtCore.QSize(93, 20))
        self.get_reduction_time.setMaximumSize(QtCore.QSize(93, 20))
        self.get_reduction_time.setObjectName("get_reduction_time")
        self.allResults.addWidget(self.get_reduction_time, 3, 4, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.frameRIGHT)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_50.setObjectName("label_50")
        self.allResults.addWidget(self.label_50, 2, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.frameRIGHT)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_53.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_53.setObjectName("label_53")
        self.allResults.addWidget(self.label_53, 2, 3, 1, 1)
        self.get_forged_len = QtWidgets.QLineEdit(self.frameRIGHT)
        self.get_forged_len.setEnabled(False)
        self.get_forged_len.setMinimumSize(QtCore.QSize(93, 20))
        self.get_forged_len.setMaximumSize(QtCore.QSize(93, 20))
        self.get_forged_len.setObjectName("get_forged_len")
        self.allResults.addWidget(self.get_forged_len, 2, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frameRIGHT)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_33.setObjectName("label_33")
        self.allResults.addWidget(self.label_33, 4, 3, 1, 1)
        self.get_piercing_reduction = QtWidgets.QLineEdit(self.frameRIGHT)
        self.get_piercing_reduction.setEnabled(False)
        self.get_piercing_reduction.setMinimumSize(QtCore.QSize(93, 20))
        self.get_piercing_reduction.setMaximumSize(QtCore.QSize(93, 20))
        self.get_piercing_reduction.setPlaceholderText("")
        self.get_piercing_reduction.setObjectName("get_piercing_reduction")
        self.allResults.addWidget(self.get_piercing_reduction, 4, 2, 1, 1)
        self.get_colib_diam = QtWidgets.QLineEdit(self.frameRIGHT)
        self.get_colib_diam.setEnabled(False)
        self.get_colib_diam.setMinimumSize(QtCore.QSize(93, 20))
        self.get_colib_diam.setMaximumSize(QtCore.QSize(93, 20))
        self.get_colib_diam.setPlaceholderText("")
        self.get_colib_diam.setObjectName("get_colib_diam")
        self.allResults.addWidget(self.get_colib_diam, 3, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frameRIGHT)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_32.setObjectName("label_32")
        self.allResults.addWidget(self.label_32, 3, 3, 1, 1)
        self.get_forged_len_9 = QtWidgets.QLineEdit(self.frameRIGHT)
        self.get_forged_len_9.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_forged_len_9.sizePolicy().hasHeightForWidth())
        self.get_forged_len_9.setSizePolicy(sizePolicy)
        self.get_forged_len_9.setMinimumSize(QtCore.QSize(1, 1))
        self.get_forged_len_9.setFrame(False)
        self.get_forged_len_9.setObjectName("get_forged_len_9")
        self.allResults.addWidget(self.get_forged_len_9, 3, 0, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.frameRIGHT)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_66.setFont(font)
        self.label_66.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_66.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_66.setObjectName("label_66")
        self.allResults.addWidget(self.label_66, 4, 1, 1, 1)
        self.get_forged_len_4 = QtWidgets.QLineEdit(self.frameRIGHT)
        self.get_forged_len_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_forged_len_4.sizePolicy().hasHeightForWidth())
        self.get_forged_len_4.setSizePolicy(sizePolicy)
        self.get_forged_len_4.setMinimumSize(QtCore.QSize(1, 1))
        self.get_forged_len_4.setFrame(False)
        self.get_forged_len_4.setObjectName("get_forged_len_4")
        self.allResults.addWidget(self.get_forged_len_4, 3, 5, 1, 1)
        self.get_forged_len_3 = QtWidgets.QLineEdit(self.frameRIGHT)
        self.get_forged_len_3.setEnabled(False)
        self.get_forged_len_3.setFrame(False)
        self.get_forged_len_3.setObjectName("get_forged_len_3")
        self.allResults.addWidget(self.get_forged_len_3, 1, 0, 1, 6)
        self.allResults.setColumnStretch(0, 1)
        self.allResults.setColumnStretch(5, 1)
        self.rightColumn.addLayout(self.allResults, 1, 0, 1, 1)
        self.report = QtWidgets.QHBoxLayout()
        self.report.setContentsMargins(0, 2, 0, 2)
        self.report.setSpacing(27)
        self.report.setObjectName("report")
        self.get_forged_len_7 = QtWidgets.QLineEdit(self.frameRIGHT)
        self.get_forged_len_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_forged_len_7.sizePolicy().hasHeightForWidth())
        self.get_forged_len_7.setSizePolicy(sizePolicy)
        self.get_forged_len_7.setMinimumSize(QtCore.QSize(1, 1))
        self.get_forged_len_7.setFrame(False)
        self.get_forged_len_7.setObjectName("get_forged_len_7")
        self.report.addWidget(self.get_forged_len_7)
        self.label_52 = QtWidgets.QLabel(self.frameRIGHT)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.report.addWidget(self.label_52)
        self.btn_save_excel = QtWidgets.QPushButton(self.frameRIGHT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save_excel.sizePolicy().hasHeightForWidth())
        self.btn_save_excel.setSizePolicy(sizePolicy)
        self.btn_save_excel.setMinimumSize(QtCore.QSize(120, 38))
        self.btn_save_excel.setMaximumSize(QtCore.QSize(120, 38))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/logo_excel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save_excel.setIcon(icon3)
        self.btn_save_excel.setIconSize(QtCore.QSize(30, 30))
        self.btn_save_excel.setObjectName("btn_save_excel")
        self.report.addWidget(self.btn_save_excel)
        self.btn_get_excel = QtWidgets.QPushButton(self.frameRIGHT)
        self.btn_get_excel.setMinimumSize(QtCore.QSize(120, 38))
        self.btn_get_excel.setMaximumSize(QtCore.QSize(120, 38))
        self.btn_get_excel.setIcon(icon3)
        self.btn_get_excel.setIconSize(QtCore.QSize(30, 30))
        self.btn_get_excel.setObjectName("btn_get_excel")
        self.report.addWidget(self.btn_get_excel)
        self.btn_get_and_save_excel = QtWidgets.QPushButton(self.frameRIGHT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_get_and_save_excel.sizePolicy().hasHeightForWidth())
        self.btn_get_and_save_excel.setSizePolicy(sizePolicy)
        self.btn_get_and_save_excel.setMinimumSize(QtCore.QSize(120, 38))
        self.btn_get_and_save_excel.setMaximumSize(QtCore.QSize(250, 38))
        self.btn_get_and_save_excel.setIcon(icon3)
        self.btn_get_and_save_excel.setIconSize(QtCore.QSize(30, 30))
        self.btn_get_and_save_excel.setObjectName("btn_get_and_save_excel")
        self.report.addWidget(self.btn_get_and_save_excel)
        self.get_forged_len_8 = QtWidgets.QLineEdit(self.frameRIGHT)
        self.get_forged_len_8.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_forged_len_8.sizePolicy().hasHeightForWidth())
        self.get_forged_len_8.setSizePolicy(sizePolicy)
        self.get_forged_len_8.setMinimumSize(QtCore.QSize(1, 1))
        self.get_forged_len_8.setFrame(False)
        self.get_forged_len_8.setObjectName("get_forged_len_8")
        self.report.addWidget(self.get_forged_len_8)
        self.report.setStretch(0, 1)
        self.report.setStretch(5, 1)
        self.rightColumn.addLayout(self.report, 2, 0, 1, 1)
        self.rightColumn.setRowStretch(0, 9)
        self.gridLayout.addLayout(self.rightColumn, 0, 0, 1, 1)
        self.both.addWidget(self.frameRIGHT, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.both, 0, 2, 1, 1)
        self.tab_analysis.addTab(self.Count, "")
        self.Analysis = QtWidgets.QWidget()
        self.Analysis.setObjectName("Analysis")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.Analysis)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.frameLeftColumn_2 = QtWidgets.QFrame(self.Analysis)
        self.frameLeftColumn_2.setMinimumSize(QtCore.QSize(332, 670))
        self.frameLeftColumn_2.setMaximumSize(QtCore.QSize(332, 11111111))
        self.frameLeftColumn_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLeftColumn_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLeftColumn_2.setObjectName("frameLeftColumn_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frameLeftColumn_2)
        self.gridLayout_10.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_10.setSpacing(4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.ent_D1_a = QtWidgets.QComboBox(self.frameLeftColumn_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ent_D1_a.sizePolicy().hasHeightForWidth())
        self.ent_D1_a.setSizePolicy(sizePolicy)
        self.ent_D1_a.setMinimumSize(QtCore.QSize(0, 20))
        self.ent_D1_a.setEditable(True)
        self.ent_D1_a.setObjectName("ent_D1_a")
        self.ent_D1_a.addItem("")
        self.gridLayout_16.addWidget(self.ent_D1_a, 1, 2, 1, 2)
        self.radio_use_temp_bil_a = QtWidgets.QRadioButton(self.frameLeftColumn_2)
        self.radio_use_temp_bil_a.setMinimumSize(QtCore.QSize(0, 20))
        self.radio_use_temp_bil_a.setObjectName("radio_use_temp_bil_a")
        self.gridLayout_16.addWidget(self.radio_use_temp_bil_a, 4, 0, 1, 4)
        self.ent_Doh_a = QtWidgets.QComboBox(self.frameLeftColumn_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ent_Doh_a.sizePolicy().hasHeightForWidth())
        self.ent_Doh_a.setSizePolicy(sizePolicy)
        self.ent_Doh_a.setMinimumSize(QtCore.QSize(0, 20))
        self.ent_Doh_a.setEditable(True)
        self.ent_Doh_a.setObjectName("ent_Doh_a")
        self.ent_Doh_a.addItem("")
        self.gridLayout_16.addWidget(self.ent_Doh_a, 3, 2, 1, 2)
        self.radio_use_init_bil_a = QtWidgets.QRadioButton(self.frameLeftColumn_2)
        self.radio_use_init_bil_a.setMinimumSize(QtCore.QSize(0, 20))
        self.radio_use_init_bil_a.setObjectName("radio_use_init_bil_a")
        self.gridLayout_16.addWidget(self.radio_use_init_bil_a, 0, 0, 1, 4)
        self.label_forged_diam_a = QtWidgets.QLabel(self.frameLeftColumn_2)
        self.label_forged_diam_a.setMinimumSize(QtCore.QSize(0, 20))
        self.label_forged_diam_a.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_forged_diam_a.setObjectName("label_forged_diam_a")
        self.gridLayout_16.addWidget(self.label_forged_diam_a, 3, 0, 1, 2)
        self.radio_use_forged_bil_a = QtWidgets.QRadioButton(self.frameLeftColumn_2)
        self.radio_use_forged_bil_a.setMinimumSize(QtCore.QSize(0, 20))
        self.radio_use_forged_bil_a.setObjectName("radio_use_forged_bil_a")
        self.gridLayout_16.addWidget(self.radio_use_forged_bil_a, 2, 0, 1, 4)
        self.label_init_diam_a = QtWidgets.QLabel(self.frameLeftColumn_2)
        self.label_init_diam_a.setMinimumSize(QtCore.QSize(0, 20))
        self.label_init_diam_a.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_init_diam_a.setObjectName("label_init_diam_a")
        self.gridLayout_16.addWidget(self.label_init_diam_a, 1, 0, 1, 2)
        self.label_71 = QtWidgets.QLabel(self.frameLeftColumn_2)
        self.label_71.setMinimumSize(QtCore.QSize(0, 20))
        self.label_71.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_71.setObjectName("label_71")
        self.gridLayout_16.addWidget(self.label_71, 7, 0, 1, 2)
        self.label_73 = QtWidgets.QLabel(self.frameLeftColumn_2)
        self.label_73.setMinimumSize(QtCore.QSize(0, 20))
        self.label_73.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_73.setObjectName("label_73")
        self.gridLayout_16.addWidget(self.label_73, 9, 0, 1, 2)
        self.radio_use_shaft_speed_a = QtWidgets.QRadioButton(self.frameLeftColumn_2)
        self.radio_use_shaft_speed_a.setMinimumSize(QtCore.QSize(0, 20))
        self.radio_use_shaft_speed_a.setObjectName("radio_use_shaft_speed_a")
        self.gridLayout_16.addWidget(self.radio_use_shaft_speed_a, 8, 0, 1, 4)
        self.radio_use_feed_angle_a = QtWidgets.QRadioButton(self.frameLeftColumn_2)
        self.radio_use_feed_angle_a.setMinimumSize(QtCore.QSize(0, 20))
        self.radio_use_feed_angle_a.setObjectName("radio_use_feed_angle_a")
        self.gridLayout_16.addWidget(self.radio_use_feed_angle_a, 6, 0, 1, 4)
        self.ent_T_a = QtWidgets.QSpinBox(self.frameLeftColumn_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ent_T_a.sizePolicy().hasHeightForWidth())
        self.ent_T_a.setSizePolicy(sizePolicy)
        self.ent_T_a.setMinimumSize(QtCore.QSize(0, 20))
        self.ent_T_a.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ent_T_a.setWrapping(False)
        self.ent_T_a.setFrame(True)
        self.ent_T_a.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ent_T_a.setAccelerated(False)
        self.ent_T_a.setKeyboardTracking(False)
        self.ent_T_a.setMinimum(1000)
        self.ent_T_a.setMaximum(1300)
        self.ent_T_a.setSingleStep(1)
        self.ent_T_a.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ent_T_a.setProperty("value", 1160)
        self.ent_T_a.setDisplayIntegerBase(10)
        self.ent_T_a.setObjectName("ent_T_a")
        self.gridLayout_16.addWidget(self.ent_T_a, 5, 2, 1, 2)
        self.ent_beta_a = QtWidgets.QComboBox(self.frameLeftColumn_2)
        self.ent_beta_a.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ent_beta_a.sizePolicy().hasHeightForWidth())
        self.ent_beta_a.setSizePolicy(sizePolicy)
        self.ent_beta_a.setMinimumSize(QtCore.QSize(0, 20))
        self.ent_beta_a.setEditable(False)
        self.ent_beta_a.setObjectName("ent_beta_a")
        self.ent_beta_a.addItem("")
        self.ent_beta_a.addItem("")
        self.ent_beta_a.addItem("")
        self.ent_beta_a.addItem("")
        self.ent_beta_a.addItem("")
        self.ent_beta_a.addItem("")
        self.ent_beta_a.addItem("")
        self.gridLayout_16.addWidget(self.ent_beta_a, 7, 2, 1, 2)
        self.ent_nd_a = QtWidgets.QSpinBox(self.frameLeftColumn_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ent_nd_a.sizePolicy().hasHeightForWidth())
        self.ent_nd_a.setSizePolicy(sizePolicy)
        self.ent_nd_a.setMinimumSize(QtCore.QSize(0, 20))
        self.ent_nd_a.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ent_nd_a.setWrapping(False)
        self.ent_nd_a.setFrame(True)
        self.ent_nd_a.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ent_nd_a.setAccelerated(False)
        self.ent_nd_a.setKeyboardTracking(False)
        self.ent_nd_a.setMinimum(1)
        self.ent_nd_a.setMaximum(100000)
        self.ent_nd_a.setSingleStep(1)
        self.ent_nd_a.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ent_nd_a.setProperty("value", 200)
        self.ent_nd_a.setDisplayIntegerBase(10)
        self.ent_nd_a.setObjectName("ent_nd_a")
        self.gridLayout_16.addWidget(self.ent_nd_a, 9, 2, 1, 2)
        self.label_75 = QtWidgets.QLabel(self.frameLeftColumn_2)
        self.label_75.setMinimumSize(QtCore.QSize(0, 20))
        self.label_75.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_75.setObjectName("label_75")
        self.gridLayout_16.addWidget(self.label_75, 5, 0, 1, 2)
        self.gridLayout_11.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.get_an_pc1_7 = QtWidgets.QLineEdit(self.frameLeftColumn_2)
        self.get_an_pc1_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_an_pc1_7.sizePolicy().hasHeightForWidth())
        self.get_an_pc1_7.setSizePolicy(sizePolicy)
        self.get_an_pc1_7.setMinimumSize(QtCore.QSize(1, 1))
        self.get_an_pc1_7.setFrame(False)
        self.get_an_pc1_7.setObjectName("get_an_pc1_7")
        self.gridLayout_11.addWidget(self.get_an_pc1_7, 5, 0, 1, 1)
        self.get_an_pc1_8 = QtWidgets.QLineEdit(self.frameLeftColumn_2)
        self.get_an_pc1_8.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_an_pc1_8.sizePolicy().hasHeightForWidth())
        self.get_an_pc1_8.setSizePolicy(sizePolicy)
        self.get_an_pc1_8.setMinimumSize(QtCore.QSize(1, 1))
        self.get_an_pc1_8.setFrame(False)
        self.get_an_pc1_8.setObjectName("get_an_pc1_8")
        self.gridLayout_11.addWidget(self.get_an_pc1_8, 3, 0, 1, 1)
        self.frame_with_reduction_a = QtWidgets.QFrame(self.frameLeftColumn_2)
        self.frame_with_reduction_a.setEnabled(True)
        self.frame_with_reduction_a.setMaximumSize(QtCore.QSize(318, 108))
        self.frame_with_reduction_a.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_with_reduction_a.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_with_reduction_a.setObjectName("frame_with_reduction_a")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_with_reduction_a)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_60 = QtWidgets.QLabel(self.frame_with_reduction_a)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.gridLayout_15.addWidget(self.label_60, 1, 1, 1, 1)
        self.set_piercing_mm_a = QtWidgets.QDoubleSpinBox(self.frame_with_reduction_a)
        self.set_piercing_mm_a.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.set_piercing_mm_a.setSingleStep(0.01)
        self.set_piercing_mm_a.setObjectName("set_piercing_mm_a")
        self.gridLayout_15.addWidget(self.set_piercing_mm_a, 1, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.frame_with_reduction_a)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.gridLayout_15.addWidget(self.label_61, 3, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.frame_with_reduction_a)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_62.setObjectName("label_62")
        self.gridLayout_15.addWidget(self.label_62, 0, 0, 1, 4)
        self.label_63 = QtWidgets.QLabel(self.frame_with_reduction_a)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.gridLayout_15.addWidget(self.label_63, 2, 0, 1, 4)
        self.label_76 = QtWidgets.QLabel(self.frame_with_reduction_a)
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.gridLayout_15.addWidget(self.label_76, 1, 3, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.frame_with_reduction_a)
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.gridLayout_15.addWidget(self.label_79, 3, 3, 1, 1)
        self.set_colib_mm_a = QtWidgets.QDoubleSpinBox(self.frame_with_reduction_a)
        self.set_colib_mm_a.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.set_colib_mm_a.setSingleStep(0.01)
        self.set_colib_mm_a.setProperty("value", 3.0)
        self.set_colib_mm_a.setObjectName("set_colib_mm_a")
        self.gridLayout_15.addWidget(self.set_colib_mm_a, 3, 0, 1, 1)
        self.set_piercing_percent_a = QtWidgets.QDoubleSpinBox(self.frame_with_reduction_a)
        self.set_piercing_percent_a.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.set_piercing_percent_a.setSingleStep(0.01)
        self.set_piercing_percent_a.setProperty("value", 2.0)
        self.set_piercing_percent_a.setObjectName("set_piercing_percent_a")
        self.gridLayout_15.addWidget(self.set_piercing_percent_a, 1, 2, 1, 1)
        self.set_colib_percent_a = QtWidgets.QDoubleSpinBox(self.frame_with_reduction_a)
        self.set_colib_percent_a.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.set_colib_percent_a.setSingleStep(0.01)
        self.set_colib_percent_a.setObjectName("set_colib_percent_a")
        self.gridLayout_15.addWidget(self.set_colib_percent_a, 3, 2, 1, 1)
        self.gridLayout_15.setColumnStretch(0, 3)
        self.gridLayout_15.setColumnStretch(1, 1)
        self.gridLayout_15.setColumnStretch(2, 3)
        self.gridLayout_15.setColumnStretch(3, 1)
        self.gridLayout_7.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_with_reduction_a, 2, 0, 1, 1)
        self.get_an_pc1_6 = QtWidgets.QLineEdit(self.frameLeftColumn_2)
        self.get_an_pc1_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_an_pc1_6.sizePolicy().hasHeightForWidth())
        self.get_an_pc1_6.setSizePolicy(sizePolicy)
        self.get_an_pc1_6.setMinimumSize(QtCore.QSize(1, 1))
        self.get_an_pc1_6.setFrame(False)
        self.get_an_pc1_6.setObjectName("get_an_pc1_6")
        self.gridLayout_11.addWidget(self.get_an_pc1_6, 7, 0, 1, 1)
        self.check_manual_reduction_a = QtWidgets.QCheckBox(self.frameLeftColumn_2)
        self.check_manual_reduction_a.setObjectName("check_manual_reduction_a")
        self.gridLayout_11.addWidget(self.check_manual_reduction_a, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frameLeftColumn_2)
        self.frame_2.setMaximumSize(QtCore.QSize(318, 124))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setLineWidth(2)
        self.frame_2.setMidLineWidth(3)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.discard_steel_a = QtWidgets.QPushButton(self.frame_2)
        self.discard_steel_a.setObjectName("discard_steel_a")
        self.gridLayout_19.addWidget(self.discard_steel_a, 3, 1, 1, 1)
        self.choose_steel_a = QtWidgets.QComboBox(self.frame_2)
        self.choose_steel_a.setEditable(True)
        self.choose_steel_a.setObjectName("choose_steel_a")
        self.choose_steel_a.addItem("")
        self.choose_steel_a.addItem("")
        self.choose_steel_a.addItem("")
        self.gridLayout_19.addWidget(self.choose_steel_a, 2, 0, 1, 1)
        self.add_steel_a = QtWidgets.QPushButton(self.frame_2)
        self.add_steel_a.setObjectName("add_steel_a")
        self.gridLayout_19.addWidget(self.add_steel_a, 2, 1, 1, 1)
        self.btn_refresh_a = QtWidgets.QPushButton(self.frame_2)
        self.btn_refresh_a.setObjectName("btn_refresh_a")
        self.gridLayout_19.addWidget(self.btn_refresh_a, 1, 1, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.frame_2)
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_77.setObjectName("label_77")
        self.gridLayout_19.addWidget(self.label_77, 0, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_19, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_2, 6, 0, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_64 = QtWidgets.QLabel(self.frameLeftColumn_2)
        self.label_64.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_64.setObjectName("label_64")
        self.gridLayout_18.addWidget(self.label_64, 0, 0, 1, 2)
        self.label_72 = QtWidgets.QLabel(self.frameLeftColumn_2)
        self.label_72.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_72.setObjectName("label_72")
        self.gridLayout_18.addWidget(self.label_72, 2, 0, 1, 2)
        self.choose_colib_a = QtWidgets.QComboBox(self.frameLeftColumn_2)
        self.choose_colib_a.setObjectName("choose_colib_a")
        self.choose_colib_a.addItem("")
        self.choose_colib_a.addItem("")
        self.choose_colib_a.addItem("")
        self.gridLayout_18.addWidget(self.choose_colib_a, 2, 2, 1, 2)
        self.ent_billet_length_a = QtWidgets.QSpinBox(self.frameLeftColumn_2)
        self.ent_billet_length_a.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ent_billet_length_a.setWrapping(False)
        self.ent_billet_length_a.setFrame(True)
        self.ent_billet_length_a.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ent_billet_length_a.setAccelerated(False)
        self.ent_billet_length_a.setKeyboardTracking(False)
        self.ent_billet_length_a.setMinimum(1)
        self.ent_billet_length_a.setMaximum(100000)
        self.ent_billet_length_a.setSingleStep(1)
        self.ent_billet_length_a.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ent_billet_length_a.setProperty("value", 3600)
        self.ent_billet_length_a.setDisplayIntegerBase(10)
        self.ent_billet_length_a.setObjectName("ent_billet_length_a")
        self.gridLayout_18.addWidget(self.ent_billet_length_a, 0, 2, 1, 2)
        self.label_74 = QtWidgets.QLabel(self.frameLeftColumn_2)
        self.label_74.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_74.setObjectName("label_74")
        self.gridLayout_18.addWidget(self.label_74, 1, 0, 1, 2)
        self.ent_Dvp_a = QtWidgets.QSpinBox(self.frameLeftColumn_2)
        self.ent_Dvp_a.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ent_Dvp_a.setWrapping(False)
        self.ent_Dvp_a.setFrame(True)
        self.ent_Dvp_a.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ent_Dvp_a.setAccelerated(False)
        self.ent_Dvp_a.setKeyboardTracking(False)
        self.ent_Dvp_a.setMinimum(1)
        self.ent_Dvp_a.setMaximum(100000)
        self.ent_Dvp_a.setSingleStep(1)
        self.ent_Dvp_a.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ent_Dvp_a.setProperty("value", 485)
        self.ent_Dvp_a.setDisplayIntegerBase(10)
        self.ent_Dvp_a.setObjectName("ent_Dvp_a")
        self.gridLayout_18.addWidget(self.ent_Dvp_a, 1, 2, 1, 2)
        self.gridLayout_11.addLayout(self.gridLayout_18, 4, 0, 1, 1)
        self.btn_analyze = QtWidgets.QPushButton(self.frameLeftColumn_2)
        self.btn_analyze.setMinimumSize(QtCore.QSize(0, 45))
        self.btn_analyze.setMaximumSize(QtCore.QSize(321, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_analyze.setFont(font)
        self.btn_analyze.setAutoDefault(True)
        self.btn_analyze.setDefault(True)
        self.btn_analyze.setFlat(False)
        self.btn_analyze.setObjectName("btn_analyze")
        self.gridLayout_11.addWidget(self.btn_analyze, 8, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.frameLeftColumn_2, 0, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setContentsMargins(-1, 4, -1, 60)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setContentsMargins(-1, -1, -1, 20)
        self.gridLayout_17.setVerticalSpacing(12)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.listWidget_a = QtWidgets.QListWidget(self.Analysis)
        self.listWidget_a.setObjectName("listWidget_a")
        self.gridLayout_17.addWidget(self.listWidget_a, 1, 0, 1, 2)
        self.label_69 = QtWidgets.QLabel(self.Analysis)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_69.setFont(font)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_69.setObjectName("label_69")
        self.gridLayout_17.addWidget(self.label_69, 0, 0, 1, 2)
        self.gridLayout_12.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.Analysis)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.get_an_pc2 = QtWidgets.QLineEdit(self.frame_4)
        self.get_an_pc2.setEnabled(False)
        self.get_an_pc2.setObjectName("get_an_pc2")
        self.gridLayout_4.addWidget(self.get_an_pc2, 1, 6, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_65.setFont(font)
        self.label_65.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_65.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_65.setObjectName("label_65")
        self.gridLayout_4.addWidget(self.label_65, 1, 5, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_82.setFont(font)
        self.label_82.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_82.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_82.setObjectName("label_82")
        self.gridLayout_4.addWidget(self.label_82, 1, 1, 1, 1)
        self.get_an_pc1_3 = QtWidgets.QLineEdit(self.frame_4)
        self.get_an_pc1_3.setEnabled(False)
        self.get_an_pc1_3.setFrame(False)
        self.get_an_pc1_3.setObjectName("get_an_pc1_3")
        self.gridLayout_4.addWidget(self.get_an_pc1_3, 1, 7, 1, 1)
        self.get_an_pc1 = QtWidgets.QLineEdit(self.frame_4)
        self.get_an_pc1.setEnabled(False)
        self.get_an_pc1.setObjectName("get_an_pc1")
        self.gridLayout_4.addWidget(self.get_an_pc1, 1, 2, 1, 1)
        self.get_an_pc1_4 = QtWidgets.QLineEdit(self.frame_4)
        self.get_an_pc1_4.setEnabled(False)
        self.get_an_pc1_4.setFrame(False)
        self.get_an_pc1_4.setObjectName("get_an_pc1_4")
        self.gridLayout_4.addWidget(self.get_an_pc1_4, 1, 3, 1, 2)
        self.get_an_pc1_5 = QtWidgets.QLineEdit(self.frame_4)
        self.get_an_pc1_5.setEnabled(False)
        self.get_an_pc1_5.setFrame(False)
        self.get_an_pc1_5.setObjectName("get_an_pc1_5")
        self.gridLayout_4.addWidget(self.get_an_pc1_5, 1, 0, 1, 1)
        self.label_an = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_an.setFont(font)
        self.label_an.setAlignment(QtCore.Qt.AlignCenter)
        self.label_an.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_an.setObjectName("label_an")
        self.gridLayout_4.addWidget(self.label_an, 0, 0, 1, 8)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(3, 1)
        self.gridLayout_4.setColumnStretch(7, 1)
        self.gridLayout_20.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_4, 1, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_12, 0, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        self.tab_analysis.addTab(self.Analysis, "")
        self.gridLayout_25.addWidget(self.tab_analysis, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_22.addWidget(self.scrollArea, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1017, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tab_analysis.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reduction Motor Load 2020.1.2"))
        self.btn_rosniti_about.setShortcut(_translate("MainWindow", "F1"))
        self.btn_vtz_about.setShortcut(_translate("MainWindow", "F1"))
        self.label_14.setText(_translate("MainWindow", "Расчет нагрузки на привод стана Ассела ТПЦ-1 АО \"ВТЗ\""))
        self.btn_secret_behind_vtz_logo.setShortcut(_translate("MainWindow", "Ctrl+Alt+Shift+E"))
        self.ent_Doh.setItemText(0, _translate("MainWindow", "120"))
        self.label_39.setText(_translate("MainWindow", "Диаметр обжатой заготовки, мм        "))
        self.label_38.setText(_translate("MainWindow", "Длина исходной заготовки, мм"))
        self.ent_D1.setItemText(0, _translate("MainWindow", "156"))
        self.label_40.setText(_translate("MainWindow", "Диаметр исходной заготовки, мм"))
        self.label_27.setText(_translate("MainWindow", "Раскатной стан"))
        self.get_real_pc.setItemText(0, _translate("MainWindow", "РС1"))
        self.get_real_pc.setItemText(1, _translate("MainWindow", "РС2"))
        self.label_28.setText(_translate("MainWindow", "Фактическая токовая нагрузка, А"))
        self.label_55.setText(_translate("MainWindow", "%"))
        self.label_59.setText(_translate("MainWindow", "На прошивном стане:"))
        self.label_54.setText(_translate("MainWindow", "мм"))
        self.set_piercing_percent.setToolTip(_translate("MainWindow", "Не рекомендуется задавать более 4%"))
        self.label_56.setText(_translate("MainWindow", "%"))
        self.label_57.setText(_translate("MainWindow", "мм"))
        self.label_58.setText(_translate("MainWindow", "На калибровочном стане:"))
        self.set_piercing_mm.setToolTip(_translate("MainWindow", "Рекомендуется задавать 3-5 мм"))
        self.set_colib_mm.setToolTip(_translate("MainWindow", "Рекомендуется задавать 3-5 мм"))
        self.set_colib_percent.setToolTip(_translate("MainWindow", "Не рекомендуется задавать более 4%"))
        self.check_manual_reduction.setText(_translate("MainWindow", "Ввести значения обжатий"))
        self.label_46.setText(_translate("MainWindow", "Калибровка валков"))
        self.label_47.setText(_translate("MainWindow", "Частота вращения двигателя, мин⁻¹"))
        self.choose_colib.setToolTip(_translate("MainWindow", "87/17-01.04 - Калибровка РосНИТИ-ВТЗ (с гребнем на входной стороне)\n"
"П20.28РН - Калибровка ВТЗ (с гребнем на выходной стороне)\n"
"П20.28-ТЗ - Калибровка ВТЗ-РосНИТИ (без гребня)"))
        self.choose_colib.setItemText(0, _translate("MainWindow", "87/17-01.04", "46546"))
        self.choose_colib.setItemText(1, _translate("MainWindow", "П20.28РН"))
        self.choose_colib.setItemText(2, _translate("MainWindow", "П20.28-ТЗ"))
        self.ent_Dvp.setToolTip(_translate("MainWindow", "Введите значение не менее 200"))
        self.label_48.setText(_translate("MainWindow", "Диаметр валков в пережиме, мм"))
        self.ent_beta.setItemText(0, _translate("MainWindow", "14"))
        self.ent_beta.setItemText(1, _translate("MainWindow", "13"))
        self.ent_beta.setItemText(2, _translate("MainWindow", "12"))
        self.ent_beta.setItemText(3, _translate("MainWindow", "11"))
        self.ent_beta.setItemText(4, _translate("MainWindow", "10"))
        self.ent_beta.setItemText(5, _translate("MainWindow", "9"))
        self.ent_beta.setItemText(6, _translate("MainWindow", "8"))
        self.label_45.setText(_translate("MainWindow", "Угол подачи, град"))
        self.ent_T.setToolTip(_translate("MainWindow", "Введите значение в диапазоне 1000-1300"))
        self.label_49.setText(_translate("MainWindow", "Исходная температура заготовки, ⁰С"))
        self.check_fact.setText(_translate("MainWindow", "Ввести фактическое значение токовой нагрузки"))
        self.btn_count.setText(_translate("MainWindow", "Расчет"))
        self.btn_count.setShortcut(_translate("MainWindow", "Return"))
        self.btn_go_to_analysis.setText(_translate("MainWindow", "Перейти к Анализу"))
        self.btn_go_to_analysis.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.discard_steel.setText(_translate("MainWindow", "-"))
        self.choose_steel.setItemText(0, _translate("MainWindow", "32ХГА"))
        self.choose_steel.setItemText(1, _translate("MainWindow", "32ййй"))
        self.choose_steel.setItemText(2, _translate("MainWindow", "30йй"))
        self.add_steel.setText(_translate("MainWindow", "+"))
        self.btn_refresh.setText(_translate("MainWindow", "Настройки"))
        self.label_51.setText(_translate("MainWindow", "Марка стали"))
        self.label_43.setText(_translate("MainWindow", "График токовых нагрузок на привод стана"))
        self.label_41.setText(_translate("MainWindow", "Раскатной Стан №2:"))
        self.label_44.setText(_translate("MainWindow", "Раскатной Стан №1:"))
        self.label_42.setText(_translate("MainWindow", "Токовая нагрузка на привод стана, А"))
        self.label_37.setText(_translate("MainWindow", "Диаметр калибра, мм:"))
        self.label_50.setText(_translate("MainWindow", "Длина обжатой заготовки, мм:"))
        self.label_53.setText(_translate("MainWindow", "Коэффициент вытяжки:"))
        self.label_33.setText(_translate("MainWindow", "Обжатие суммарное, %:"))
        self.label_32.setText(_translate("MainWindow", "Время обжатия, с:"))
        self.label_66.setText(_translate("MainWindow", "Обжатие на раскатном стане, %:"))
        self.label_52.setText(_translate("MainWindow", "Сводный отчет:"))
        self.btn_save_excel.setText(_translate("MainWindow", "Сохранить"))
        self.btn_get_excel.setText(_translate("MainWindow", "Открыть"))
        self.btn_get_and_save_excel.setText(_translate("MainWindow", "Сохранить \n"
"и открыть"))
        self.tab_analysis.setTabText(self.tab_analysis.indexOf(self.Count), _translate("MainWindow", "Расчет"))
        self.ent_D1_a.setItemText(0, _translate("MainWindow", "156"))
        self.radio_use_temp_bil_a.setText(_translate("MainWindow", "Использовать температуру заготовки"))
        self.ent_Doh_a.setItemText(0, _translate("MainWindow", "120"))
        self.radio_use_init_bil_a.setText(_translate("MainWindow", "Использовать диаметр исходной заготовки"))
        self.label_forged_diam_a.setText(_translate("MainWindow", "Диаметр обжатой заготовки, мм"))
        self.radio_use_forged_bil_a.setText(_translate("MainWindow", "Использовать диаметр обжатой заготовки"))
        self.label_init_diam_a.setText(_translate("MainWindow", "Диаметр исходной заготовки, мм"))
        self.label_71.setText(_translate("MainWindow", "Угол подачи, град"))
        self.label_73.setText(_translate("MainWindow", "Частота вращения двигателя, мин⁻¹"))
        self.radio_use_shaft_speed_a.setText(_translate("MainWindow", "Использовать частоту вращения двигателя"))
        self.radio_use_feed_angle_a.setText(_translate("MainWindow", "Использовать угол подачи"))
        self.ent_T_a.setToolTip(_translate("MainWindow", "Введите значение в диапазоне 1000-1300"))
        self.ent_beta_a.setItemText(0, _translate("MainWindow", "14"))
        self.ent_beta_a.setItemText(1, _translate("MainWindow", "13"))
        self.ent_beta_a.setItemText(2, _translate("MainWindow", "12"))
        self.ent_beta_a.setItemText(3, _translate("MainWindow", "11"))
        self.ent_beta_a.setItemText(4, _translate("MainWindow", "10"))
        self.ent_beta_a.setItemText(5, _translate("MainWindow", "9"))
        self.ent_beta_a.setItemText(6, _translate("MainWindow", "8"))
        self.label_75.setText(_translate("MainWindow", "Исходная температура заготовки, ⁰С"))
        self.label_60.setText(_translate("MainWindow", "мм"))
        self.set_piercing_mm_a.setToolTip(_translate("MainWindow", "Рекомендуется задавать 3-5 мм"))
        self.label_61.setText(_translate("MainWindow", "мм"))
        self.label_62.setText(_translate("MainWindow", "На прошивном стане:"))
        self.label_63.setText(_translate("MainWindow", "На калибровочном стане:"))
        self.label_76.setText(_translate("MainWindow", "%"))
        self.label_79.setText(_translate("MainWindow", "%"))
        self.set_colib_mm_a.setToolTip(_translate("MainWindow", "Рекомендуется задавать 3-5 мм"))
        self.set_piercing_percent_a.setToolTip(_translate("MainWindow", "Не рекомендуется задавать более 4%"))
        self.set_colib_percent_a.setToolTip(_translate("MainWindow", "Не рекомендуется задавать более 4%"))
        self.check_manual_reduction_a.setText(_translate("MainWindow", "Ввести значение обжатия"))
        self.discard_steel_a.setText(_translate("MainWindow", "-"))
        self.choose_steel_a.setItemText(0, _translate("MainWindow", "32ХГА"))
        self.choose_steel_a.setItemText(1, _translate("MainWindow", "32ййй"))
        self.choose_steel_a.setItemText(2, _translate("MainWindow", "30йй"))
        self.add_steel_a.setText(_translate("MainWindow", "+"))
        self.btn_refresh_a.setText(_translate("MainWindow", "Настройки"))
        self.label_77.setText(_translate("MainWindow", "Марка стали"))
        self.label_64.setText(_translate("MainWindow", "Длина исходной заготовки, мм"))
        self.label_72.setText(_translate("MainWindow", "Калибровка валков"))
        self.choose_colib_a.setToolTip(_translate("MainWindow", "87/17-01.04 - Калибровка РосНИТИ-ВТЗ (с гребнем на входной стороне)\n"
"П20.28РН - Калибровка ВТЗ (с гребнем на выходной стороне)\n"
"П20.28-ТЗ - Калибровка ВТЗ-РосНИТИ (без гребня)"))
        self.choose_colib_a.setItemText(0, _translate("MainWindow", "87/17-01.04", "46546"))
        self.choose_colib_a.setItemText(1, _translate("MainWindow", "П20.28РН"))
        self.choose_colib_a.setItemText(2, _translate("MainWindow", "П20.28-ТЗ"))
        self.label_74.setText(_translate("MainWindow", "Диаметр валков в пережиме, мм"))
        self.btn_analyze.setText(_translate("MainWindow", "Анализ"))
        self.btn_analyze.setShortcut(_translate("MainWindow", "Return"))
        self.label_69.setText(_translate("MainWindow", "График зависимости токовых нагрузок от диаметра исходной/обжатой заготовки"))
        self.label_65.setText(_translate("MainWindow", "Раскатной Стан №2:"))
        self.label_82.setText(_translate("MainWindow", "Раскатной Стан №1:"))
        self.label_an.setText(_translate("MainWindow", "Максимально/Минимально допустимое значение варьируемого параметра"))
        self.tab_analysis.setTabText(self.tab_analysis.indexOf(self.Analysis), _translate("MainWindow", "Анализ"))
import source_rc
