# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prog_rasch_interface_v6.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(875, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(91, 11, 691, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(193, 193, 193)")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 111, 321, 431))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 2)
        self.ent_beta = QtWidgets.QComboBox(self.layoutWidget)
        self.ent_beta.setEditable(True)
        self.ent_beta.setObjectName("ent_beta")
        self.ent_beta.addItem("")
        self.gridLayout.addWidget(self.ent_beta, 4, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.add_steel = QtWidgets.QPushButton(self.layoutWidget)
        self.add_steel.setObjectName("add_steel")
        self.gridLayout.addWidget(self.add_steel, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.ent_Doh = QtWidgets.QComboBox(self.layoutWidget)
        self.ent_Doh.setEditable(True)
        self.ent_Doh.setObjectName("ent_Doh")
        self.ent_Doh.addItem("")
        self.gridLayout.addWidget(self.ent_Doh, 2, 2, 1, 2)
        self.ent_D1 = QtWidgets.QComboBox(self.layoutWidget)
        self.ent_D1.setEditable(True)
        self.ent_D1.setObjectName("ent_D1")
        self.ent_D1.addItem("")
        self.gridLayout.addWidget(self.ent_D1, 0, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 2)
        self.btn_refresh = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_refresh.setObjectName("btn_refresh")
        self.gridLayout.addWidget(self.btn_refresh, 9, 2, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        self.discard_steel = QtWidgets.QPushButton(self.layoutWidget)
        self.discard_steel.setObjectName("discard_steel")
        self.gridLayout.addWidget(self.discard_steel, 9, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 2)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 8, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.comboBox_5, 7, 2, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 2)
        self.ent_T = QtWidgets.QSpinBox(self.layoutWidget)
        self.ent_T.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ent_T.setWrapping(False)
        self.ent_T.setFrame(True)
        self.ent_T.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ent_T.setAccelerated(False)
        self.ent_T.setKeyboardTracking(False)
        self.ent_T.setMaximum(100000)
        self.ent_T.setSingleStep(1)
        self.ent_T.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ent_T.setProperty("value", 1160)
        self.ent_T.setDisplayIntegerBase(10)
        self.ent_T.setObjectName("ent_T")
        self.gridLayout.addWidget(self.ent_T, 3, 2, 1, 2)
        self.ent_Dvp = QtWidgets.QSpinBox(self.layoutWidget)
        self.ent_Dvp.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ent_Dvp.setWrapping(False)
        self.ent_Dvp.setFrame(True)
        self.ent_Dvp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ent_Dvp.setAccelerated(False)
        self.ent_Dvp.setKeyboardTracking(False)
        self.ent_Dvp.setMaximum(100000)
        self.ent_Dvp.setSingleStep(1)
        self.ent_Dvp.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ent_Dvp.setProperty("value", 485)
        self.ent_Dvp.setDisplayIntegerBase(10)
        self.ent_Dvp.setObjectName("ent_Dvp")
        self.gridLayout.addWidget(self.ent_Dvp, 5, 2, 1, 2)
        self.ent_nd = QtWidgets.QSpinBox(self.layoutWidget)
        self.ent_nd.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ent_nd.setWrapping(False)
        self.ent_nd.setFrame(True)
        self.ent_nd.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ent_nd.setAccelerated(False)
        self.ent_nd.setKeyboardTracking(False)
        self.ent_nd.setMaximum(100000)
        self.ent_nd.setSingleStep(1)
        self.ent_nd.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ent_nd.setProperty("value", 200)
        self.ent_nd.setDisplayIntegerBase(10)
        self.ent_nd.setObjectName("ent_nd")
        self.gridLayout.addWidget(self.ent_nd, 6, 2, 1, 2)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.spinBox.setWrapping(False)
        self.spinBox.setFrame(True)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox.setAccelerated(False)
        self.spinBox.setKeyboardTracking(False)
        self.spinBox.setMaximum(100000)
        self.spinBox.setSingleStep(1)
        self.spinBox.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.spinBox.setProperty("value", 3600)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 2, 1, 2)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(361, 111, 492, 391))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.get_PC2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.get_PC2.setEnabled(False)
        self.get_PC2.setObjectName("get_PC2")
        self.gridLayout_2.addWidget(self.get_PC2, 3, 3, 1, 1)
        self.get_PC1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.get_PC1.setEnabled(False)
        self.get_PC1.setPlaceholderText("")
        self.get_PC1.setObjectName("get_PC1")
        self.gridLayout_2.addWidget(self.get_PC1, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 4)
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget1)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 1, 0, 1, 4)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 4)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(781, 11, 71, 91))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(21, 11, 71, 91))
        self.label_18.setObjectName("label_18")
        self.btn_count = QtWidgets.QPushButton(self.centralwidget)
        self.btn_count.setGeometry(QtCore.QRect(111, 551, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_count.setFont(font)
        self.btn_count.setObjectName("btn_count")
        self.btn_set_colib = QtWidgets.QPushButton(self.centralwidget)
        self.btn_set_colib.setGeometry(QtCore.QRect(21, 551, 81, 51))
        self.btn_set_colib.setObjectName("btn_set_colib")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(361, 551, 491, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.btn_get_pdf = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_get_pdf.setObjectName("btn_get_pdf")
        self.horizontalLayout.addWidget(self.btn_get_pdf)
        self.btn_get_excel = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_get_excel.setObjectName("btn_get_excel")
        self.horizontalLayout.addWidget(self.btn_get_excel)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setWindowModality(QtCore.Qt.NonModal)
        self.line.setGeometry(QtCore.QRect(10, 430, 341, 20))
        self.line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line.setAutoFillBackground(False)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setWindowModality(QtCore.Qt.NonModal)
        self.line_3.setGeometry(QtCore.QRect(0, 440, 21, 91))
        self.line_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_3.setAutoFillBackground(False)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setWindowModality(QtCore.Qt.NonModal)
        self.line_4.setGeometry(QtCore.QRect(340, 440, 21, 91))
        self.line_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_4.setAutoFillBackground(False)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setWindowModality(QtCore.Qt.NonModal)
        self.line_2.setGeometry(QtCore.QRect(10, 520, 341, 21))
        self.line_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_2.setAutoFillBackground(False)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.get_forged_len = QtWidgets.QLineEdit(self.centralwidget)
        self.get_forged_len.setEnabled(False)
        self.get_forged_len.setGeometry(QtCore.QRect(580, 510, 190, 20))
        self.get_forged_len.setObjectName("get_forged_len")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(408, 510, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.btn_count.raise_()
        self.btn_set_colib.raise_()
        self.layoutWidget.raise_()
        self.label_17.raise_()
        self.label_14.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_18.raise_()
        self.line.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_2.raise_()
        self.get_forged_len.raise_()
        self.label_16.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 875, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ent_D1, self.ent_Doh)
        MainWindow.setTabOrder(self.ent_Doh, self.ent_beta)
        MainWindow.setTabOrder(self.ent_beta, self.comboBox_5)
        MainWindow.setTabOrder(self.comboBox_5, self.get_PC1)
        MainWindow.setTabOrder(self.get_PC1, self.get_PC2)
        MainWindow.setTabOrder(self.get_PC2, self.btn_get_pdf)
        MainWindow.setTabOrder(self.btn_get_pdf, self.btn_get_excel)
        MainWindow.setTabOrder(self.btn_get_excel, self.listWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_14.setText(_translate("MainWindow", "Расчет нагрузки на главный привод стана Ассела ТПЦ-1 АО \"ВТЗ\""))
        self.label_9.setText(_translate("MainWindow", "Калибровка валков"))
        self.ent_beta.setItemText(0, _translate("MainWindow", "14"))
        self.label_2.setText(_translate("MainWindow", "Длина исходной заготовки, мм"))
        self.add_steel.setText(_translate("MainWindow", "+"))
        self.label_3.setText(_translate("MainWindow", "Диаметр обжатой заготовки, мм"))
        self.ent_Doh.setItemText(0, _translate("MainWindow", "120"))
        self.ent_D1.setItemText(0, _translate("MainWindow", "156"))
        self.label_6.setText(_translate("MainWindow", "Диаметр валков в пережиме, мм"))
        self.btn_refresh.setText(_translate("MainWindow", "Настройки"))
        self.label_4.setText(_translate("MainWindow", "Исходная температура, град цельс"))
        self.discard_steel.setText(_translate("MainWindow", "-"))
        self.label_7.setText(_translate("MainWindow", "Частота вращения двигателя, мин -1"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "32ХГА"))
        self.label_8.setText(_translate("MainWindow", "Марка стали"))
        self.label.setText(_translate("MainWindow", "Диаметр исходной заготовки, мм"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Штатная"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Задать вручную"))
        self.label_5.setText(_translate("MainWindow", "Угол подачи, град"))
        self.label_15.setText(_translate("MainWindow", "График токовых нагрузок на главный привод"))
        self.label_10.setText(_translate("MainWindow", "Максимальная токовая нагрузка на главный привод, кА"))
        self.label_12.setText(_translate("MainWindow", "РС №2:"))
        self.label_11.setText(_translate("MainWindow", "РС №1:"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><img src=\'C:\\Users\\Zavarcev-NA\\Desktop\\Лого РосНИТИ рус.png\' width=71 height=91/></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><img src=\'C:\\Users\\Zavarcev-NA\\Desktop\\vtz_logo — копия.jpg\' width=71 height=91/></html>"))
        self.btn_count.setText(_translate("MainWindow", "Расчет"))
        self.btn_set_colib.setText(_translate("MainWindow", "Задать \n"
"калибровку"))
        self.label_13.setText(_translate("MainWindow", "Сводный отчет:"))
        self.btn_get_pdf.setText(_translate("MainWindow", "PDF"))
        self.btn_get_excel.setText(_translate("MainWindow", "Excel"))
        self.label_16.setText(_translate("MainWindow", "Длина обжатой заготовки:"))
